version: '3.4'

services:
 
  itops.healthmonitor:
    image: ${DOCKER_REGISTRY-}itopshealthmonitor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5100:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80